/*!
 * © Sitecore Corporation A/S. All rights reserved. Sitecore® is a registered trademark of Sitecore Corporation A/S.
 */

// All the configureation are align with ckeditor configuration in canvas- so check if any new
// update should also be updated in canvas editor

import {
  Alignment,
  Autoformat,
  AutoImage,
  AutoLink,
  BlockQuote,
  Bold,
  DataFilter,
  DataSchema,
  Essentials,
  FindAndReplace,
  Font,
  GeneralHtmlSupport,
  Heading,
  HeadingOption,
  HorizontalLine,
  HtmlComment,
  Image,
  ImageCaption,
  ImageEditing,
  ImageInsert,
  ImageResize,
  ImageStyle,
  ImageToolbar,
  Indent,
  IndentBlock,
  Italic,
  Link,
  LinkImage,
  List,
  ListProperties,
  Paragraph,
  PasteFromOffice,
  RemoveFormat,
  SourceEditing,
  StandardEditingMode,
  Strikethrough,
  Style,
  Subscript,
  Superscript,
  Table,
  TableCaption,
  TableCellProperties,
  TableColumnResize,
  TableProperties,
  TableToolbar,
  Underline,
  type EditorConfig,
} from 'ckeditor5';
import { AddPhone } from './custom-plugins/add-phone';
import { InternalLink } from './custom-plugins/internal-link';
import { ResetFieldValue } from './custom-plugins/reset-value';
import { SelectMedia } from './custom-plugins/select-media';

const DEFAULT_PLUGINS = [
  Alignment,
  AutoImage,
  AutoLink,
  Bold,
  BlockQuote,
  DataFilter,
  DataSchema,
  Essentials,
  FindAndReplace,
  GeneralHtmlSupport,
  Heading,
  HorizontalLine,
  HtmlComment,
  Image,
  ImageCaption,
  ImageInsert,
  ImageResize,
  ImageStyle,
  ImageToolbar,
  Indent,
  IndentBlock,
  Italic,
  Link,
  LinkImage,
  List,
  ListProperties,
  Paragraph,
  RemoveFormat,
  SourceEditing,
  StandardEditingMode,
  Strikethrough,
  Style,
  Subscript,
  Superscript,
  Table,
  TableCaption,
  TableCellProperties,
  TableColumnResize,
  TableProperties,
  TableToolbar,
  Underline,
  SelectMedia,
  ResetFieldValue,
  PasteFromOffice,
  AddPhone,
  InternalLink,
  Autoformat,
  Font,
  SourceEditing,
  ImageEditing,
];

export const DEFAULT_CONFIG: EditorConfig = {
  toolbar: {
    items: [
      'bold',
      'italic',
      'underline',
      'blockQuote',
      {
        label: 'Formatting',
        icon: 'text',
        items: ['strikethrough', 'subscript', 'superscript', '|', 'removeFormat'],
      },
      'fontColor',
      'fontBackgroundColor',
      '|',
      'heading',
      '|',
      'alignment',
      'bulletedList',
      'numberedList',
      '|',
      'outdent',
      'indent',
      '|',
      'link',
      'internalLink',
      'phoneLink',
      '|',
      {
        label: 'Insert',
        withText: false,
        icon: 'plus',
        items: ['horizonSelectMedia', 'insertTable', 'HorizontalLine'],
      },
      '|',
      'sourceEditing',
      '|',
      'horizonResetFieldValue',
    ],
    shouldNotGroupWhenFull: true,
  },
  alignment: {
    options: ['left', 'right', 'center', 'justify'],
  },
  heading: {
    options: [
      { model: 'paragraph', title: 'P', class: 'ck-heading_paragraph' },
      { model: 'heading1', view: 'h1', title: 'H1', class: 'ck-heading_heading1' },
      { model: 'heading2', view: 'h2', title: 'H2', class: 'ck-heading_heading2' },
      { model: 'heading3', view: 'h3', title: 'H3', class: 'ck-heading_heading3' },
      { model: 'heading4', view: 'h4', title: 'H4', class: 'ck-heading_heading4' },
      { model: 'heading5', view: 'h5', title: 'H5', class: 'ck-heading_heading5' },
      { model: 'heading6', view: 'h6', title: 'H6', class: 'ck-heading_heading6' },
    ] as HeadingOption[],
  },
  ui: {
    poweredBy: {
      position: 'inside',
      side: 'right',
      label: '',
      horizontalOffset: 5,
      verticalOffset: 5,
    },
  },
  // Allow most HTML tags for rich text editing, excluding XSS-prone tags like <script>, <iframe>, <input type="file">
  htmlSupport: {
    allow: [
      {
        name: /.*/,
        attributes: true,
        classes: true,
        styles: true,
      },
    ],
    disallow: [
      { name: /^(script|frame|object|embed|form|meta|base|xml)$/ },
      {
        name: 'input',
        attributes: {
          type: 'file',
        },
      },
    ],
  },
  image: {
    toolbar: [
      'imageTextAlternative',
      'toggleImageCaption',
      '|',
      'imageStyle:inline',
      'imageStyle:wrapText',
      'imageStyle:breakText',
      '|',
      'linkImage',
    ],
  },
  table: {
    contentToolbar: ['tableColumn', 'tableRow', 'mergeTableCells', 'tableCellProperties', 'tableProperties'],
  },
  language: 'en',
  list: {
    properties: {
      styles: true,
      startIndex: true,
      reversed: true,
    },
  },
  link: {
    defaultProtocol: 'https://',
    decorators: {
      openInNewTab: {
        mode: 'manual',
        label: 'Open in new tab',
        attributes: {
          target: '_blank',
        },
      },
    },
  },
  plugins: DEFAULT_PLUGINS,
};
