/*!
 * © Sitecore Corporation A/S. All rights reserved. Sitecore® is a registered trademark of Sitecore Corporation A/S.
 */

import { Page, PageHierarchy } from './page.types';

export class PageTestData {
  static readonly mockPageHierarchy: PageHierarchy = {
    page: {
      url: 'https://example.com/page',
      icon: 'page_icon',
      versionName: '1.0',
      revision: '123456',
      createdAt: '2024-04-30T12:00:00Z',
      updatedAt: '2024-04-30T13:00:00Z',
      createdBy: 'user123',
      template: {
        id: 'template123',
        name: 'Template Name',
        path: '/templates/template123',
        baseTemplateIds: ['2bb25752-b3bc-4f13-b9cb-38b906d21a33', '77b1399f-5f30-4643-a054-59bbb1c7c62c'],
        displayName: 'Template display Name',
      },
      workflow: {
        id: 'workflow123',
        displayName: 'Workflow Name',
        finalState: true,
        canEdit: true,
        warnings: [],
        icon: 'workflow_icon',
        commands: [],
      },
      publishing: {
        isPublishable: true,
        hasPublishableVersion: true,
        isAvailableToPublish: true,
        validFromDate: '2024-04-30T12:00:00Z',
        validToDate: '2024-05-01T12:00:00Z',
      },
      route: '/page/route',
      finalLayout: 'default',
      sharedLayout: 'page-shared-layout',
      layoutEditingKind: 'FINAL',
      id: 'page123',
      name: 'Page Name',
      displayName: 'Page Display Name',
      language: 'en',
      version: 1,
      templateId: 'template123',
      parentId: 'parent123',
      hasPresentation: true,
      hasChildren: false,
      permissions: {
        canAdmin: true,
        canWrite: true,
        canCreate: true,
        canDelete: true,
        canRename: true,
        canRead: true,
        canPublish: true,
      },
      locking: {
        canUnlock: true,
        isLocked: false,
        lockedBy: '',
        lockedByCurrentUser: false,
      },
      insertOptions: [],
      hasVersions: true,
      updatedBy: '',
      path: 'page-path',
    },
    children: [
      {
        url: 'https://example.com/child-page',
        icon: 'child_page_icon',
        versionName: '1.0',
        revision: '654321',
        createdAt: '2024-05-01T12:00:00Z',
        updatedAt: '2024-05-01T13:00:00Z',
        createdBy: 'user456',
        template: {
          id: 'template456',
          name: 'Child Template',
          path: '/templates/template456',
          baseTemplateIds: ['2bb25752-b3bc-4f13-b9cb-38b906d21a33', '77b1399f-5f30-4643-a054-59bbb1c7c62c'],
          displayName: 'Template display Name',
        },
        workflow: {
          id: 'workflow456',
          displayName: 'Child Workflow',
          finalState: true,
          canEdit: true,
          warnings: [],
          icon: 'child_workflow_icon',
          commands: [],
        },
        publishing: {
          isPublishable: true,
          hasPublishableVersion: true,
          isAvailableToPublish: true,
          validFromDate: '2024-05-01T12:00:00Z',
          validToDate: '2024-05-02T12:00:00Z',
        },
        route: '/child-page/route',
        finalLayout: 'default',
        sharedLayout: 'page-shared-layout',
        layoutEditingKind: 'FINAL',
        id: 'childPage123',
        name: 'Child Page Name',
        displayName: 'Child Page Display Name',
        language: 'en',
        version: 1,
        templateId: 'template456',
        parentId: 'page123',
        hasPresentation: true,
        hasChildren: false,
        permissions: {
          canAdmin: true,
          canWrite: true,
          canCreate: true,
          canDelete: true,
          canRename: true,
          canRead: true,
          canPublish: true,
        },
        locking: {
          canUnlock: true,
          isLocked: false,
          lockedBy: '',
          lockedByCurrentUser: false,
        },
        insertOptions: [],
        hasVersions: true,
        updatedBy: '',
        path: 'page-path',
      },
    ],
    ancestors: [
      {
        url: 'https://example.com/ancestor-page',
        icon: 'ancestor_page_icon',
        versionName: '1.0',
        revision: '789012',
        createdAt: '2024-04-29T12:00:00Z',
        updatedAt: '2024-04-29T13:00:00Z',
        createdBy: 'user789',
        template: {
          id: 'template789',
          name: 'Ancestor Template',
          path: '/templates/template789',
          baseTemplateIds: ['2bb25752-b3bc-4f13-b9cb-38b906d21a33', '77b1399f-5f30-4643-a054-59bbb1c7c62c'],
          displayName: 'Template display Name',
        },
        workflow: {
          id: 'workflow789',
          displayName: 'Ancestor Workflow',
          finalState: true,
          canEdit: true,
          warnings: [],
          icon: 'ancestor_workflow_icon',
          commands: [],
        },
        publishing: {
          isPublishable: true,
          hasPublishableVersion: true,
          isAvailableToPublish: true,
          validFromDate: '2024-04-29T12:00:00Z',
          validToDate: '2024-04-30T12:00:00Z',
        },
        route: '/ancestor-page/route',
        finalLayout: 'default',
        sharedLayout: 'page-shared-layout',
        layoutEditingKind: 'FINAL',
        id: 'ancestorPage123',
        name: 'Ancestor Page Name',
        displayName: 'Ancestor Page Display Name',
        language: 'en',
        version: 1,
        templateId: 'template789',
        parentId: '',
        hasPresentation: true,
        hasChildren: true,
        permissions: {
          canAdmin: true,
          canWrite: true,
          canCreate: true,
          canDelete: true,
          canRename: true,
          canRead: true,
          canPublish: true,
        },
        locking: {
          canUnlock: true,
          isLocked: false,
          lockedBy: '',
          lockedByCurrentUser: false,
        },
        insertOptions: [],
        hasVersions: true,
        updatedBy: '',
        path: 'page-path',
      },
    ],
    siblings: [],
  };

  static readonly mockPage: Page = {
    url: 'https://example.com',
    icon: 'page-icon.png',
    versionName: 'Version 1.0',
    revision: '123456',
    createdAt: '2024-04-30T12:00:00Z',
    updatedAt: '2024-04-30T12:00:00Z',
    createdBy: 'John Doe',
    template: {
      id: 'templateId123',
      name: 'Template Name',
      path: '/path/to/template',
      baseTemplateIds: ['2bb25752-b3bc-4f13-b9cb-38b906d21a33', '77b1399f-5f30-4643-a054-59bbb1c7c62c'],
      displayName: 'Template display Name',
    },
    workflow: {
      id: 'workflowId123',
      displayName: 'Workflow Name',
      finalState: true,
      canEdit: true,
      warnings: [
        {
          id: 'warningId1',
          errorCode: 'NoAccessRightItemWrite',
          message: 'Workflow error message',
        },
      ],
      icon: 'workflow-icon.png',
      commands: [
        {
          id: 'commandId1',
          displayName: 'Command 1',
          icon: 'command1-icon.png',
        },
      ],
    },
    publishing: {
      isPublishable: true,
      hasPublishableVersion: true,
      isAvailableToPublish: true,
      validFromDate: '2024-04-30T12:00:00Z',
      validToDate: '2024-05-30T12:00:00Z',
    },
    route: '/page-route',
    finalLayout: 'Default Layout',
    sharedLayout: 'page-shared-layout',
    layoutEditingKind: 'FINAL',
    id: 'pageId123',
    name: 'Page Name',
    displayName: 'Page Display Name',
    language: 'en',
    version: 1,
    templateId: 'templateId123',
    parentId: 'parentId123',
    hasPresentation: true,
    hasChildren: true,
    permissions: {
      canAdmin: true,
      canWrite: true,
      canCreate: true,
      canDelete: true,
      canRename: true,
      canRead: true,
      canPublish: true,
    },
    locking: {
      canUnlock: true,
      isLocked: false,
      lockedBy: '',
      lockedByCurrentUser: false,
    },

    insertOptions: [],
    hasVersions: true,
    updatedBy: '',
    path: 'page-path',
  };

  static readonly mockAncestors: Page[] = [
    {
      url: 'https://example.com/ancestor-page',
      icon: 'ancestor_page_icon',
      versionName: '1.0',
      revision: '789012',
      createdAt: '2024-04-29T12:00:00Z',
      updatedAt: '2024-04-29T13:00:00Z',
      createdBy: 'user789',
      publishing: {
        isPublishable: true,
        hasPublishableVersion: true,
        isAvailableToPublish: true,
        validFromDate: '2024-04-29T12:00:00Z',
        validToDate: '2024-04-30T12:00:00Z',
      },
      route: '/ancestor-page/route',
      id: 'ancestorPage123',
      name: 'Ancestor Page Name',
      displayName: 'Ancestor Page Display Name',
      language: 'en',
      version: 1,
      templateId: 'template789',
      parentId: '',
      hasPresentation: true,
      hasChildren: true,
      permissions: {
        canAdmin: true,
        canWrite: true,
        canCreate: true,
        canDelete: true,
        canRename: true,
        canRead: true,
        canPublish: true,
      },
      locking: {
        canUnlock: true,
        isLocked: false,
        lockedBy: '',
        lockedByCurrentUser: false,
      },
    } as Partial<Page> as Page,
  ];

  static readonly mockVersions: Page[] = [
    {
      url: 'https://example.com/child-page',
      icon: 'child_page_icon',
      versionName: '1.0',
      revision: '654321',
      createdAt: '2024-05-01T12:00:00Z',
      updatedAt: '2024-05-01T13:00:00Z',
      createdBy: 'user456',
      template: {
        id: 'template456',
        name: 'Child Template',
        path: '/templates/template456',
        baseTemplateIds: ['2bb25752-b3bc-4f13-b9cb-38b906d21a33', '77b1399f-5f30-4643-a054-59bbb1c7c62c'],
        displayName: 'Template display Name',
      },
      workflow: {
        id: 'workflow456',
        displayName: 'Child Workflow',
        finalState: true,
        canEdit: true,
        warnings: [],
        icon: 'child_workflow_icon',
        commands: [],
      },
      publishing: {
        isPublishable: true,
        hasPublishableVersion: true,
        isAvailableToPublish: true,
        validFromDate: '2024-05-01T12:00:00Z',
        validToDate: '2024-05-02T12:00:00Z',
      },
      route: '/child-page/route',
      finalLayout: 'default',
      sharedLayout: 'page-shared-layout',
      layoutEditingKind: 'FINAL',
      id: 'childPage123',
      name: 'Child Page Name',
      displayName: 'Child Page Display Name',
      language: 'en',
      version: 1,
      templateId: 'template456',
      parentId: 'page123',
      hasPresentation: true,
      hasChildren: false,
      permissions: {
        canAdmin: true,
        canWrite: true,
        canCreate: true,
        canDelete: true,
        canRename: true,
        canRead: true,
        canPublish: true,
      },
      locking: {
        canUnlock: true,
        isLocked: false,
        lockedBy: '',
        lockedByCurrentUser: false,
      },
      insertOptions: [],
      hasVersions: true,
      updatedBy: '',
      path: 'page-path',
    },
  ];
}
