//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Horizon.Integration.Tests.Ui.ApiHelpers.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sitecore.Horizon.Integration.Tests.Ui.ApiHelpers.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;configuration xmlns:patch=&quot;http://www.sitecore.net/xmlconfig/&quot;&gt;
        ///  &lt;sitecore&gt;
        ///    &lt;settings&gt;
        ///      &lt;setting name=&quot;DeviceDetection.Enabled&quot; value=&quot;false&quot; /&gt;
        ///    &lt;/settings&gt;
        ///  &lt;/sitecore&gt;
        ///&lt;/configuration&gt;
        ///.
        /// </summary>
        internal static string DisableDeviceDetection {
            get {
                return ResourceManager.GetString("DisableDeviceDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;configuration xmlns:patch=&quot;http://www.sitecore.net/xmlconfig/&quot;&gt;
        ///  &lt;sitecore&gt;
        ///    &lt;settings&gt;
        ///      &lt;setting name=&quot;Horizon.SegmentDataController.CacheEnabled&quot; value=&quot;false&quot; /&gt;
        ///    &lt;/settings&gt;
        ///  &lt;/sitecore&gt;
        ///&lt;/configuration&gt;
        ///.
        /// </summary>
        internal static string DisableHorizonAnalyticsCache {
            get {
                return ResourceManager.GetString("DisableHorizonAnalyticsCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;configuration xmlns:patch=&quot;http://www.sitecore.net/xmlconfig/&quot;&gt;
        ///  &lt;sitecore&gt;
        ///    &lt;settings&gt;
        ///      &lt;setting name=&quot;Analytics.AutoDetectBots&quot; value=&quot;false&quot; /&gt;
        ///    &lt;/settings&gt;
        ///  &lt;/sitecore&gt;
        ///&lt;/configuration&gt;
        ///.
        /// </summary>
        internal static string DisableRobotDetection {
            get {
                return ResourceManager.GetString("DisableRobotDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;configuration xmlns:patch=&quot;http://www.sitecore.net/xmlconfig/&quot;&gt;
        ///  &lt;sitecore&gt;
        ///    &lt;settings&gt;
        ///      &lt;setting name=&quot;Xdb.Enabled&quot; value=&quot;false&quot; /&gt;
        ///    &lt;/settings&gt;
        ///  &lt;/sitecore&gt;
        ///&lt;/configuration&gt;
        ///.
        /// </summary>
        internal static string DisableXdb {
            get {
                return ResourceManager.GetString("DisableXdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;configuration xmlns:patch=&quot;http://www.sitecore.net/xmlconfig/&quot;&gt;
        ///  &lt;sitecore&gt;
        ///    &lt;settings&gt;
        ///      &lt;setting name=&quot;Sitecore.Web.IsAuthorizationBypassAllowed&quot; value=&quot;true&quot; /&gt;
        ///    &lt;/settings&gt;
        ///  &lt;/sitecore&gt;
        ///&lt;/configuration&gt;
        ///.
        /// </summary>
        internal static string IgnoreAntiCSRFTokens {
            get {
                return ResourceManager.GetString("IgnoreAntiCSRFTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System.Security.Authentication
        ///@inherits System.Web.Mvc.WebViewPage
        ///@using Sitecore.Mvc
        ///@{
        ///  Layout = null;
        ///}
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html lang=&quot;en&quot; xml:lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;title&gt;
        ///    @Html.Sitecore().Field(&quot;title&quot;, new
        ///    {
        ///        DisableWebEdit = true
        ///    })
        ///  &lt;/title&gt;
        ///  &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///  &lt;lin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MvcDebugLayout {
            get {
                return ResourceManager.GetString("MvcDebugLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MvcLayout {
            get {
                object obj = ResourceManager.GetObject("MvcLayout", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MvcRendering {
            get {
                object obj = ResourceManager.GetObject("MvcRendering", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MvcRendering2 {
            get {
                object obj = ResourceManager.GetObject("MvcRendering2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MvcRendering3 {
            get {
                object obj = ResourceManager.GetObject("MvcRendering3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MvcRenderingStart {
            get {
                object obj = ResourceManager.GetObject("MvcRenderingStart", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MvcRenderingWithAllFieldTypes {
            get {
                object obj = ResourceManager.GetObject("MvcRenderingWithAllFieldTypes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SampleLayout {
            get {
                object obj = ResourceManager.GetObject("SampleLayout", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--
        ///
        ///Purpose: This include file adds a new site definition
        ///
        ///To enable this, rename this file so that it has a &quot;.config&quot; extension and 
        ///change all the parameters to suit your own scenario
        ///
        ///Notice how &quot;patch:before&quot; is used to insert the site definition BEFORE the 
        ///existing &lt;site name=&quot;website&quot; ...&gt; element 
        ///
        ///You can use &quot;patch:before&quot; and &quot;patch:after&quot; as an attribute of an inserted 
        ///element to specify an insertion point for the new element. Both accept an 
        ///XPath relative to the parent node of t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SiteDefinitionPatternConfig {
            get {
                return ResourceManager.GetString("SiteDefinitionPatternConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%@ Page Language=&quot;c#&quot; Inherits=&quot;System.Web.UI.Page&quot; CodePage=&quot;65001&quot; %&gt;
        ///
        ///&lt;%@ OutputCache Location=&quot;None&quot; VaryByParam=&quot;none&quot; %&gt;
        ///&lt;%@ Import Namespace=&quot;System.Security.Authentication&quot; %&gt;
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head runat=&quot;server&quot;&gt;
        ///    &lt;title&gt;Welcome to Sitecore&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;/&gt;
        ///    &lt;meta name=&quot;CODE_LANGUAGE&quot; content=&quot;C#&quot;/&gt;
        ///    &lt;m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebFormsDebugLayout {
            get {
                return ResourceManager.GetString("WebFormsDebugLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] XsltRenderingStart {
            get {
                object obj = ResourceManager.GetObject("XsltRenderingStart", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] XsltSampleRendering {
            get {
                object obj = ResourceManager.GetObject("XsltSampleRendering", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
