// © Sitecore Corporation A/S. All rights reserved. Sitecore® is a registered trademark of Sitecore Corporation A/S.

using System;
using System.Collections.Generic;

namespace Sitecore.Pages.E2EFramework.UI.Tests.ApiHelpers.XMApps.Types;

public class Site
{
    public string id { get; set; }
    public string name { get; set; }
    public string description { get; set; }
    public string displayName { get; set; }
    public Thumbnail thumbnail { get; set; }
    public string collectionId { get; set; }
    public DateTime created { get; set; }
    public string createdBy { get; set; }
    public int sortOrder { get; set; }
    public Access access { get; set; }
    public List<string> languages { get; set; }
    public List<Host> hosts { get; set; }
    public List<string> supportedLanguages { get; set; }
    public Settings settings { get; set; }
    public Properties properties { get; set; }

    public class Settings
    {
        public string linkProvider { get; set; }
        public string isSiteThumbnailSource { get; set; }
        public string sxaLinkable { get; set; }
        public string idp { get; set; }
        public string thumbnailsRootPath { get; set; }
        public string generateThumbnails { get; set; }
    }

    public class Thumbnail
    {
        public string url { get; set; }
        public string rootPath { get; set; }
        public bool autogenerated { get; set; }
    }

    public class Properties
    {
        public string siteDefinitionPath { get; set; }
        public string rootPath { get; set; }
        public string siteDefinitionID { get; set; }
        public string startItem { get; set; }
        public string isInternal { get; set; }
        public string SxaSiteTemplate { get; set; }
        public string IsSxaSite { get; set; }
        public string siteTemplate { get; set; }
        public string sharedSite { get; set; }
    }

    public class RenderingHost
    {
        public string id { get; set; }
        public string name { get; set; }
        public string appName { get; set; }
        public string layoutServiceConfiguration { get; set; }
        public string serverSideRenderingEngineEndpointUrl { get; set; }
        public string serverSideRenderingEngineApplicationUrl { get; set; }
    }

    public class LanguageSettings
    {
        public string defaultLanguage { get; set; }
        public bool languageEmbedding { get; set; }
        public bool itemLanguageFallback { get; set; }
        public bool fieldLanguageFallback { get; set; }
    }

    public class Permissions
    {
        public bool canAdmin { get; set; }
        public bool canWrite { get; set; }
        public bool canCreate { get; set; }
        public bool canDelete { get; set; }
        public bool canRename { get; set; }
        public bool canRead { get; set; }
        public bool canPublish { get; set; }
        public bool canDuplicate { get; set; }
    }

    public class AnalyticsIdentifiers
    {
        public string en { get; set; }
    }

    public class Host
    {
        public string id { get; set; }
        public string name { get; set; }
        public List<string> hostnames { get; set; }
        public string targetHostname { get; set; }
        public string homePageId { get; set; }
        public RenderingHost renderingHost { get; set; }
        public Permissions permissions { get; set; }
        public Settings settings { get; set; }
        public Properties properties { get; set; }
        public AnalyticsIdentifiers analyticsIdentifiers { get; set; }
        public LanguageSettings languageSettings { get; set; }
        public DateTime created { get; set; }
        public string createdBy { get; set; }
    }

    public class Access
    {
        public bool canAdmin { get; set; }
        public bool canWrite { get; set; }
        public bool canCreate { get; set; }
        public bool canDelete { get; set; }
        public bool canRename { get; set; }
        public bool canRead { get; set; }
        public bool canPublish { get; set; }
        public bool canDuplicate { get; set; }
    }
}
