---
ID: "703baa96-c732-439a-abb6-1b3eb029dd85"
Parent: "026a1373-1e17-45a4-81f5-9b30774f07b4"
Template: "668b1ee6-417c-43a7-8b6b-5e6fc664bc88"
Path: /sitecore/content/SXAHeadlessTenant/Shared site/Presentation/Partial Designs
BranchID: "45cf9f42-b3ac-4412-aab9-f8441c7e448e"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{703ABB6D-BE33-4F9D-97FF-EE1571A14C81}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250304T180736Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin@pagestest.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin@pagestest.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7863745e-160c-46ea-839a-515ef9033b7a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin@pagestest.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250304T180737Z
