---
ID: "0e741327-fabb-418c-b1f6-a3a5b67e6ec0"
Parent: "2a229a1c-62f0-490a-aeb2-9de4521cd79d"
Template: "2a229a1c-62f0-490a-aeb2-9de4521cd79d"
Path: /sitecore/templates/Project/SXAHeadlessTenant/Page Designs/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {4CE98DBC-9C94-4723-97E1-A4A41EFB9937}
    {1105B8F8-1E00-426B-BF1F-C840742D827B}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250304T180511Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin@pagestest.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin@pagestest.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "163059e8-89a2-4d07-82b4-92c4519f5236"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin@pagestest.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250304T180513Z
