# IMPORTANT: This file was automatically generated by an AI assistant
# based on existing C# test files. It serves as a starting point for BDD features
# and REQUIRES SIGNIFICANT MANUAL REVIEW AND REFINEMENT to ensure correctness,
# capture the full intent of the original tests, and adhere to proper Gherkin conventions.
#
# Original C# test files are located in the same directory or subdirectories.
# Please compare and update these Gherkin scenarios accordingly.
#

# Feature automatically generated from: tests/SItecore.Pages.E2EFramework.UI.Tests/Features/OpenPage.cs
Feature: Open page

  # Scenario automatically generated from method: GoBackAndForwardBrowserHistoryByContentTree
  # TODO: Review and refine this auto-generated scenario.
  Scenario: Go back and forward browser history by content tree
    Given an initial system state # Placeholder
    When an action is performed   # Placeholder
    Then an outcome is asserted   # Placeholder

  # Scenario automatically generated from method: XSSScriptingInURLIsNotExecuted
  # TODO: Review and refine this auto-generated scenario.
  Scenario: X S S scripting in U R L is not executed
    Given an initial system state # Placeholder
    When an action is performed   # Placeholder
    Then an outcome is asserted   # Placeholder


# Feature automatically generated from: tests/SItecore.Pages.E2EFramework.UI.Tests/Features/ABnTests/AbnTestListTests.cs
Feature: Abn test list tests

  # Scenario automatically generated from method: OpenAbnTestList_CheckAppliedConfigurations
  # TODO: Review and refine this auto-generated scenario.
  Scenario: Open abn test list check applied configurations
    Given an initial system state # Placeholder
    When an action is performed   # Placeholder
    Then an outcome is asserted   # Placeholder

  # Scenario automatically generated from method: OpenAbnTestList_CheckLinkToXMApps
  # TODO: Review and refine this auto-generated scenario.
  Scenario: Open abn test list check link to X M apps
    Given an initial system state # Placeholder
    When an action is performed   # Placeholder
    Then an outcome is asserted   # Placeholder

  # Scenario automatically generated from method: OpenAbnTestList_CheckList
  # TODO: Review and refine this auto-generated scenario.
  Scenario: Open abn test list check list
    Given an initial system state # Placeholder
    When an action is performed   # Placeholder
    Then an outcome is asserted   # Placeholder

  # Scenario automatically generated from method: OpenAbnTestList_GoToTest
  # TODO: Review and refine this auto-generated scenario.
  Scenario: Open abn test list go to test
    Given an initial system state # Placeholder
    When an action is performed   # Placeholder
    Then an outcome is asserted   # Placeholder


# Feature automatically generated from: tests/SItecore.Pages.E2EFramework.UI.Tests/Features/Editor/Canvas.cs
Feature: Canvas

  # Scenario automatically generated from method: UserHoversAllFieldTypes_TheyAreHighlightedAndHaveTags
  # TODO: Review and refine this auto-generated scenario.
  Scenario: User hovers all field types they are highlighted and have tags
    Given an initial system state # Placeholder
    When an action is performed   # Placeholder
    Then an outcome is asserted   # Placeholder

  # Scenario automatically generated from method: UserSelectsAllFieldTypes_TheyHaveChipsWithTitlesAndHighlighted
  # TODO: Review and refine this auto-generated scenario.
  Scenario: User selects all field types they have chips with titles and highlighted
    Given an initial system state # Placeholder
    When an action is performed   # Placeholder
    Then an outcome is asserted   # Placeholder

  # Scenario automatically generated from method: UserHoversRendering_ItIsHighlighted
  # TODO: Review and refine this auto-generated scenario.
  Scenario: User hovers rendering it is highlighted
    Given an initial system state # Placeholder
    When an action is performed   # Placeholder
    Then an outcome is asserted   # Placeholder

  # Scenario automatically generated from method: UserClicksFields_TheyAreDimmed
  # TODO: Review and refine this auto-generated scenario.
  Scenario: User clicks fields they are dimmed
    Given an initial system state # Placeholder
    When an action is performed   # Placeholder
    Then an outcome is asserted   # Placeholder

  # Scenario automatically generated from method: Chrome_Re_discovery_verification
  # TODO: Review and refine this auto-generated scenario.
  Scenario: Chrome re discovery verification
    Given an initial system state # Placeholder
    When an action is performed   # Placeholder
    Then an outcome is asserted   # Placeholder
